Repository Projeto-Des-SW/certifai-backend, pull requests merged in 2025-09, with the labels that each got.

#30 [CF-0009] fix: adicionando nome para entidade prova
  src/main/java/br/com/certifai/dto/ProvaDTO.java
  src/main/java/br/com/certifai/model/Prova.java
  src/main/java/br/com/certifai/requests/MontarProvaRequest.java
  src/main/java/br/com/certifai/service/impl/ProvaService.java
  src/test/java/br/com/certifai/controllers/ProvaControllerIntegrationTest.java
  src/test/java/br/com/certifai/services/ProvaServiceTest.java
Labels: bug

#32 [CF-0011] feat: adicionando conexão entre prova e questões
  src/main/java/br/com/certifai/dto/ProvaDTO.java
  src/main/java/br/com/certifai/mappers/IProvaMapper.java
  src/main/java/br/com/certifai/model/Prova.java
  src/main/java/br/com/certifai/service/impl/ProvaService.java
Labels: enhancement

#31 [CF-0010] add: checklist
  src/main/java/br/com/certifai/controller/impl/ChecklistController.java
  src/main/java/br/com/certifai/controller/interfaces/ChecklistApi.java
  src/main/java/br/com/certifai/dto/ChecklistDTO.java
  src/main/java/br/com/certifai/mappers/IChecklistMapper.java
  src/main/java/br/com/certifai/mappers/IItemChecklistMapper.java
  src/main/java/br/com/certifai/model/Checklist.java
  src/main/java/br/com/certifai/model/ItemChecklist.java
  src/main/java/br/com/certifai/service/impl/ChecklistService.java
Labels: enhancement

#33 [CF-0012] atualizando readme
  README.md
Labels: documentation
